# setup postgres
version: '3'
services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=cochef_dev'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=postgres'
    ports:
      - '6543:5432'
volumes:
  postgres-data:
